server:
  port: 8080
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_gm?useSSL=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  mvc:
    view:
      prefix: /
      suffix: .html
#mybatis
mybatis:
  #  µÃÂ…®√Ë
  type-aliases-package: it.gm.springboot.pojo


